	<?php
				$jours=array(	'Lundi' 	=> 'Isnin',
								'Mardi' 	=> 'Selasa',
								'Mercredi' 	=> 'Rabu',
								'Jeudi' 	=> 'Khamis',
								'Vendredi' 	=> 'Jumaat',
								'Samedi' 	=> 'Sabtu',
								'Dimanche' 	=> 'Ahad',
								'Maintenant' => 'Sekarang',
								'Aujourd\'hui' => 'Hari ini',
								'Hier' => 'Semalam',
								'Demain' => 'Esok',
								'Soir' => 'Malam',
								'Matin' => 'Pagi',
								);
				
				$verb1=array(	'Je parle' 	=> 'Saya bercakap',
								'Je marche' => 'Saya berjalan',
								'Je lis' 	=> 'Saya membaca',
								'J\'achete' => 'Saya membeli',
								'Je regarde ' => 'Saya melihat ',
								'Je mange ' => 'Saya makan',
								'Je couris'	=> 'Saya berlari',
								'Je vais' 	=> 'Saya pergi',
								'Je faire' 	=> 'Saya membuat',
								'Je cherche' => 'Saya mencari',
								'Je travail' => 'Saya berkerja',
								'Je bois' 	=> 'Saya minum',
								'J\'ecoute' 	=> 'Saya mendengar',
						);
						
				$verb2=array(	'J\'ai parlé' 	=> 'Saya telah cakap',
								'J\'ai marche' => 'Saya telah berjalan',
								'Je lis' 	=> 'Saya telah membaca',
								'J\'achete' => 'Saya telah membeli',
								'Je regarde ' => 'Saya telah melihat',
							
						);
				
				$verb3=array(	'Je vais parler' 	=> 'Saya akan cakap',
								'Je vais marcher' => 'Saya akan jalan',
								'Je vais lire ' 	=> 'Saya akan baca',
								'Je vais acheter' => 'Saya akan beli',
								'Je vais regarde ' => 'Saya akan lihat ',
								
						);
												
				$objet=array('la calculatrice' => 'kalkulator',
						'le crayon' => 'pensil',
						'une feuille de papier' => 'kertas' ,
						'le dictionnaire' => 'kamus',
						'le sac' => 'beg',
						'le stylo' => 'pen',
						'le livre' => 'buku',
						'la regle' => 'pembaris',
						'l\'horloge' => 'jam',
						'les ciseaux' => 'gunting',
						'la table' => 'meja',
						'la chaise' => 'kerusi', 
					);		
					
				$famille=array('Le père' => 'Ayah', 
						'La mère' => 'Emak', 
						'Le frère' => 'Abang',
						'La sœur' => 'Kakak',
						'Le fils' => 'Anak lelaki',
						'Le fille' => 'Anak perempuan',
						'L\'enfant' => 'Kanak-kanak',
						'Le bébé' => 'Bayi',
						'Le mari' => 'Suami',
						'La femme' => 'Isteri',
						'Le fiancé(e)' => 'Tunang',
						'Le grand-père' => 'Datuk', 
						'le grand-mère' => 'Nenek', 
						'les petits-enfants' => 'Cucu',	
						'l\’oncle' => 'Pakcik',
						'la tante' => 'Makcik',
						'le neveu' => 'Anak buah lelaki /Anak saudara lelaki',
						'la nièce' => 'Anak buah perempuan /Anak saudara perempuan',
						'le beau-père (1)' => 'Ayah Tiri',
						'le beau-père (2)' => 'Ayah mertua',
						'la belle-mère (1)' => 'Emak tiri',
						'la belle-mère (2)' => 'Emak mertua',
						'le cousin(e)' => 'Sepupu',
						'le beau-frère' => 'Abang ipar',
						'la belle-sœur' => 'sister in-law');	
					
				$nourri=array('la viande' => 'daging',
							'le poulet' => 'ayam',
							'la dinde' => 'ayam belanda',
							'le pain' => 'roti',
							'le rir' => 'nasi',
							'les nouilles' => 'mee',
							'les pâtes' => 'pasta',
							'le beurre' => 'mentega',
							'le fromage' => 'keju',
							'le lait' => 'susu',
							'les eoufs' => 'telur',
							'la farine' => 'tepung',
							'le gâteau' => 'kek',
							'le miel' => 'madu',
							'le sucre' => 'gula',
							'les bonsbons' => 'gula gula',
							);
							
				$couleur=array('Blanc' => 'Putih',
								'Noir' => 'Hitam',
								'Gris' => 'Kelabu',
								'Rouge' => 'Merah',
								'Jeune' => 'Kuning',
								'Bleu' => 'Biru',
								'Orange' => 'Oren',
								'Vert' => 'Hijau',
								'Violet' => 'Ungu',
								'Marron' => 'Coklat',
								'Rose' => 'Merah jambu',
								'Clair' => 'cair, eg: Biru cair',
								'Foncé' => 'pekat, eg: Hijau pekat',
								);
				$nb=array('0' => 'kosong',
							'1' => 'satu',
							'2' => 'dua',
							'3' => 'tiga',
							'4' => 'empat',
							'5' => 'lima',
							'6' => 'enam',
							'7' => 'tujuh',
							'8' => 'lapan',
							'9' => 'sembilan',
							'10' => 'sepuluh',
							);
							
				$animal=array('l\'ours' => 'beruang', 
								'le chameau' => 'Unta', 
								'la poule' => 'ayam', 
								'le crocodile' => 'buaya', 
								'l\'âne' => 'keldai', 
								'le cert' => 'rusa', 
								'le canard' => 'itik', 
								'le lion' => 'singa', 
								'l\'aigle' => 'burung helang', 
								'la girafe' => 'zirafah', 
								'l\'éléphan' => 'gajah', 
								'la grenouille' => 'katak', 
								'le singe' => 'monyet', 
								'le souris' => 'tikus', 
								'le cochon' => 'babi',
								'le lapin' => 'arnab',
								'le requin' => 'ikan jerung',
								'le mouton' => 'kambing biri-biri',
								'le serpent' => 'ular',
								'l\'écureuil' => 'tupai',
								'le loup' => 'serigala',
								'le renard' => 'musang',
								'l\'oiseau' => 'burung',
								'la vache' => 'lembu',
								'le chien' => 'anjing',
								'le cheval' => 'kuda',
								'le chat' => 'kucing',
								'le poisson' => 'ikan',
								);			

					$fruits=array('la banane' => 'pisang',
								'la pomme' => 'epal',
								'l\’orange' => 'oren',
								'le melon' => 'tembikai susu',
								'la datte' => 'kurma',
								'le raisin' => 'anggur',
								'le citron' => 'limau',
								'la fraise' => 'strawberi',
								'la pastèque' => 'tembikai',
								'le haricot vert' => 'kacang panjang',
								'le maïs' => 'jagung',
								'l\'onion' => 'bawang',
								'la pomme de terre' => 'kentang',
								'l\'ail' => 'bawang putih',
								'le concombre' => 'timun',
								'le champignon' => 'cendawan',
								'le gingembre' => 'halia',
								'la carotte' => 'lobak merah',
								);			
								
?>	
